name: ${project.name}
author: ${project.organization.name}
version: ${project.version}

main: ${bukkitMain}

commands:
    shutdown:
        description: Shutdowns the server
        usage: /shutdown <reason>